[build]
  functions = "functions"
  publish   = "public"

[[redirects]]
  from = "/api/cgdcontract"
  to   = "/.netlify/functions/cgdcontract"
  status = 200
  force  = true
  name = "govspending-proxy"
  main = "govspending.js"
  compatibility_date = "2024-10-01"